# Default values for nops-k8s-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/nops-io/nops-k8s-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "deploy"

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true

cronjob:
  schedule: "5 * * * *"

env_variables:
  # Required paramters
  APP_PROMETHEUS_SERVER_ENDPOINT: "http://prometheus.nops-k8s-agent.svc.cluster.local:9090"
  APP_NOPS_K8S_AGENT_CLUSTER_ID: "DEMO"
  APP_AWS_S3_BUCKET: ""
  APP_AWS_S3_PREFIX: ""
  # Optional parameters
  APP_ENV: "live"
  APP_NOPS_K8S_AGENT_TIMEOUT: "120"
  APP_NOPS_K8S_COLLECTOR_HOST : "app.nops.io"
  APP_NOPS_K8S_COLLECTOR_PORT: "443"
  APP_NOPS_K8S_COLLECTOR_NO_SSL: ""
  APP_NOPS_K8S_COLLECTOR_SKIP_SSL_VALIDATION: ""
  APP_NOPS_K8S_AGENT_PROM_TOKEN: ""
  APP_DEBUG: False
  # set from helm command line
  AWS_DEFAULT_REGION: "us-west-2"
